components:
  schemas:
    Cart:
      type: object
      properties:
        products:
          type: array
          description: Productos dentro del carrito
          products:
            $ref: '#/components/schemas/CartItem'
      example: 
        products:
          product0: 64dc35e9b1a6f4bbfbf63db5
          product1: 64dc35e9b1a6f4bbfbf63db7
    CartItem:
      type: object
      properties:
        product_id:
          type: integer
          format: int64
          description: ID del producto dentro del carrito
        quantity:
          type: integer
          format: int32
          description: Cantidad del producto dentro del carrito
      example: 
        products:
          product: 64dc35e9b1a6f4bbfbf63db5
          quantity: 2
    NewCart:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/NewCartItem'
      example: 
        products:
          product: 64dc35e9b1a6f4bbfbf63db5
          quantity: 3
    NewCartItem:
      type: object
      properties:
        product_id:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
      example: 
        products:
          product: 64dc35e9b1a6f4bbfbf63db5
          quantity: 4
    UpdateCart:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/UpdateCartItem'
      example: 
        products:
          product: 64dc35e9b1a6f4bbfbf63db8
          quantity: 5
    UpdateCartItem:
      type: object
      properties:
        product_id:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
      example: 
        products:
          product: 64dc35e9b1a6f4bbfbf63db8
          quantity: 5
  responses:
    cart:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        payload:
          $ref: '#/components/schemas/Cart'
      example:
        status: success
        payload:
          id: ID del carrito
          user: ID del propietario del carrito
          products:
            - product_id: ID de producto 
              quantity: Cantidad del producto añadido
    getCarts:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        payload:
          $ref: '#/components/schemas/Cart'
      example:
        status: success
        payload:
          id: ID del carrito
          user: ID del propietario del carrito
          products:
            - product_id: ID del producto añadido
              quantity: Cantidad del producto añadido
    createCart:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        payload:
          $ref: "#/components/schemas/Cart"
      example:
        status: success
        payload:
          id: ID del nuevo carrito
          products:
            - product_id: ID de un producto añadido
              quantity: Cantidad del producto añadido
    updateCart:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        payload:
          $ref: '#/components/schemas/Cart'
      example:
        status: success
        payload:
          id: ID del carrito actualizado
          products:
            - product_id: ID de los productos del carrito actualizado
              quantity: Cantidad de los productos del carrito
    destroyCart:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        message:
          type: string
          description: Mensaje de éxito
      example:
        status: success
        message: Carrito eliminado exitosamente
    destroyProductCart:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        message:
          type: string
          description: Mensaje de éxito
      example:
        status: success
        message: Producto/s eliminado exitosamente
    purchaseCart:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        message:
          type: string
          description: Mensaje de éxito
      example:
        status: success
        payload: ID del ticket creado
        message: Compra dirigida a la seccion de tickets, informacion enviada al usuario.
    notFound:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        from:
          type: string
          description: Descripción del endpoint del error
        message:
          type: string
          description: Descripción del error
      example:
        status: error
        from: GET /api/carts controller
        message: Not found documents
    notFoundOne:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        from:
          type: string
          description: Descripción del endpoint del error
        message:
          type: string
          description: Descripción del error
      example:
        status: error
        from: GET /api/carts/{pid} controller
        message: Not found document
    documentError:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        from:
          type: string
          description: Descripción del endpoint del error
        message:
          type: string
          description: Descripción del error
      example:
        status: error
        from: POST /api/carts controller
        message: Cannot create document
    documentEmpty:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        from:
          type: string
          description: Descripción del endpoint del error
        message:
          type: string
          description: Descripción del error
      example:
        status: error
        from: POST /api/carts controller
        message: Incomplete values
    cartEmpty:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        from:
          type: string
          description: Descripción del endpoint del error
        message:
          type: string
          description: Descripción del error
      example:
        status: error
        from: POST /api/carts/purchase-cart controller
        message: Document is empty
    clientError:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        from:
          type: string
          description: Descripción del endpoint del error
        message:
          type: string
          description: Descripción del error
      example:
        status: error
        from: PUT /api/carts controller
        message: Incomplete values
    notLogged:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        message: 
          type: string
          description: Descripcion del error
      example: 
        status: error
        from: POST /api/carts/mycart controller
        message: Se requiere estar logueago para hacer esta operacion
    serverError:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        from:
          type: string
          description: Descripción del endpoint del error
        message:
          type: string
          description: Descripción del error
      example:
        status: fatal
        from: HTTP /api/carts controller
        message: Server crashes

paths:
  /api/carts:
    get:
      summary: Obtener la lista completa de carritos, acceso unicamente de admin
      tags:
        - Carts
      responses:
        '200':
          description: Exito en la lectura de carritos
          content:
            application/json:
              schema:
                $ref: '#/components/responses/cart'
        '404':
          description: No se encontraron los documentos
          content:
            application/json:
              schema:
                $ref: '#/components/responses/notFound'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'
    post:
      summary: Crear un nuevo carrito, acceso unicamente de admin
      tags:
        - Carts
      requestBody:
        required: true
        description: Objeto con las propiedades necesarias para crear un nuevo carrito
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCart'
      responses:
        '201':
          description: Éxito en la creación de un nuevo carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/createCart'
        '400':
          description: Faltante de campos en el objeto de creación de carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/documentError'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'

  /api/carts/{cid}:
    get:
      summary: Obtener información de un carrito específico, acceso unicamente de admin
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          description: ID del carrito
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Exito en la lectura del carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/getCarts'
        '404':
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/notFoundOne'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'
    put:
      summary: Actualizar información de un carrito específico, acceso unicamente de admin
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          description: ID del carrito
          required: true
          type: integer
          format: int64
      requestBody:
        required: true
        description: Objeto con las propiedades a actualizar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCart'
      responses:
        '200':
          description: Éxito en la actualización del carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/updateCart'
        '400':
          description: Se requieren los campos a actualizar
          content:
            application/json:
              schema:
                $ref: '#/components/responses/clientError'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'
    delete:
      summary: Eliminar un carrito específico, acceso unicamente de admin
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          description: ID del carrito
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Éxito en la eliminación del carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/destroyCart'
        '404':
          description: Carrito no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/notFoundOne'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'
  /mycart:
    get:
      summary: Obtener el carrito del usuario logueado
      tags:
        - Carts
      responses:
        '200':
          description: Éxito en la obtencion del carrito del usuario
          content:
            application/json:
              schema:
                $ref: '#/components/responses/cart'
        '404':
          description: Error en la obtencion del carrito del usuario ya que no esta logueado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/notLogged'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'
  /mycart/product/{pid}:
    post:
      summary: Agregar un producto mediante su id en el carrito del usuario logueado
      tags:
        - Carts
      parameters:
        - name: pid
          in: path
          description: ID del producto
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Éxito en agregar un producto al carrito del usuario logueado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/getCarts'
        '404':
          description: No se encuentra el producto enviado para agregar al carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/notFoundOne'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'
    put:
      summary: Modificar la cantidad de un producto mediante su id en el carrito del usuario logueado
      tags:
        - Carts
      parameters:
        - name: pid
          in: path
          description: ID del producto
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Éxito en la obtencion y modificacion del carrito del usuario logueado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/updateCart'
        '404':
          description: No se encuentra el producto enviado dentro del carrito para ser modificado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/notFoundOne'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'
  /mycart/products:
    delete:
      summary: Eliminar todos los productos del carrito del usuario logueado
      tags:
        - Carts
      responses:
        '200':
          description: Éxito en la eliminacion de los productos del carrito del usuario logueado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/destroyProductCart'
        '404':
          description: Error en la eliminacion de los productos debido a que el carrito se encuentra vacio
          content:
            application/json:
              schema:
                $ref: '#/components/responses/cartEmpty'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'
  /mycart/products/{pid}:
    delete:
      summary: Eliminar un producto mediante su id del carrito del usuario logueado
      tags:
        - Carts
      parameters:
        - name: pid
          in: path
          description: ID del producto
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Éxito en la eliminacion de un producto del carrito del usuario logueado
          content:
            application/json:
              schema:
                $ref: '#/components/responses/destroyProductCart'
        '404':
          description: Error en la eliminacion de un producto debido a que no se encuentra en el carrito
          content:
            application/json:
              schema:
                $ref: '#/components/responses/notFoundOne'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'
  /purchase-cart:
    post:
      summary: Realizar la compra del carrito del usuario logueado para la creacion del ticket
      tags:
        - Carts
      responses:
        '200':
          description: Éxito en la compra del carrito y creacion del ticket
          content:
            application/json:
              schema:
                $ref: '#/components/responses/purchaseCart'
        '404':
          description: Error en la compra de carrito debido a que se encuentra vacio
          content:
            application/json:
              schema:
                $ref: '#/components/responses/cartEmpty'
        '500':
          description: Error caida de servidor
          content:
            application/json:
              schema:
                $ref: '#components/responses/serverError'